{% set name = "matplotview" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matplotview-{{ version }}.tar.gz
  sha256: 877566f57520e10930b187e1d0afcae4c0b4f1a6ab6a56093fd593299e1a2505

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.1
    - numpy

test:
  imports:
    - matplotview
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matplotlib/matplotview
  summary: A library for creating lightweight views of matplotlib axes.
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
